"""add document chunk embedding

Revision ID: 1ed2530eec8c
Revises: e01cb6c9aa11
Create Date: 2026-06-01 17:51:16.012885

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed2530eec8c'
down_revision: Union[str, Sequence[str], None] = 'e01cb6c9aa11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=8), nullable=True),
    )
    op.add_column('document_chunks', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_dimensions')
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
