"""add document file hash index

Revision ID: 42abb46cdedc
Revises: 32bfadf5771c
Create Date: 2026-05-07 16:48:19.471471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42abb46cdedc'
down_revision: Union[str, Sequence[str], None] = '32bfadf5771c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    # ### end Alembic commands ###
