"""create document assets

Revision ID: e349934e4513
Revises: 42abb46cdedc
Create Date: 2026-05-09 16:39:12.145442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e349934e4513'
down_revision: Union[str, Sequence[str], None] = '42abb46cdedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('placeholder', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_assets_asset_type'), 'document_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_document_assets_document_id'), 'document_assets', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_assets_placeholder'), 'document_assets', ['placeholder'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_assets_placeholder'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_document_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_asset_type'), table_name='document_assets')
    op.drop_table('document_assets')
    # ### end Alembic commands ###
